template = "https://github.com/giellalt/template-lang-und"
rev_id = 221
template_sha = "e7fdee9ae36d733638ddba15d7566415c602f750"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wyr"
__UND2C__ = "wyr"
__UNDEFINED__ = "Wayor√≥"
__UND__ = "wyr"
