template = "https://github.com/giellalt/template-lang-und"
rev_id = 222
template_sha = "a4b7a17ad6ee4c01316e4673baa43b277e00b3f2"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wyr"
__UND2C__ = "wyr"
__UNDEFINED__ = "Wayor√≥"
__UND__ = "wyr"
