template = "https://github.com/giellalt/template-lang-und"
rev_id = 268
template_sha = "444a55f5c0c0489e8f1dcde2639b74c44c24dffb"

[replacements]
__GLOTTOLOG_ID__ = "wayo1238"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wyr"
__UND2C__ = "wyr"
__UNDEFINED__ = "Wayor√≥"
__UND__ = "wyr"
