template = "https://github.com/giellalt/template-lang-und"
rev_id = 261
template_sha = "eaa0621ef7403d653282fabf176060ed3c95ebf4"

[replacements]
__GLOTTOLOG_ID__ = "wayo1238"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wyr"
__UND2C__ = "wyr"
__UNDEFINED__ = "Wayor√≥"
__UND__ = "wyr"
